### ISSUE TITLE
Be able to split a page into two when the case-comparision is on

### ISSUE THREAD

**Issue by ggsdc** [baobabsoluciones/cornflow#118]
@pchtsp wrote:

"Specifically for the "ad-hoc" page, where statistics for two solutions can be seen and compared."

**Comment by HelenaCA** [comment]
Closed. New ticket for this enhancement here: https://github.com/baobabsoluciones/cornflow-ui/issues/48

**Comment by HelenaCA** [comment]
Closed. New ticket for this enhancement here: https://github.com/baobabsoluciones/cornflow-ui/issues/48
