### ISSUE TITLE
Add logging of actions in app

### ISSUE THREAD

**Issue by ggsdc** [baobabsoluciones/cornflow#121]
@pchtsp wrote:

"internal usage of the app (without calling cornflow-server) should be logged in some place (locally or remotely)"
and
"options:
http://log4javascript.org/
https://sentry.io/welcome/
https://logrocket.com/for/react/

Apparently, sentry is the most well known."

**Comment by HelenaCA** [comment]
Closed. New ticket for this enhancement: https://github.com/baobabsoluciones/cornflow-ui/issues/49
