### ISSUE TITLE
Create calendar component for cornflow-app

### ISSUE THREAD

**Issue by ggsdc** [baobabsoluciones/cornflow#129]
Create a shared component that can be inherited in cornflow-app that contains the calendar.

**Comment by ggsdc** [comment]
Search for alternatives of the calendar library, open source, or try to create our own calendar / agenda component.

**Comment by marioncottard** [comment]
What is wrong with the one that is being used for now ? What would we need to add/change in our component?

**Comment by ggsdc** [comment]
> What is wrong with the one that is being used for now ? What would we need to add/change in our component?

The component we use is correct, but we have very similar code in two different apps to use that calendar, we should do as we have done with the ganttVis and have our own component on top of the existing component that we can reuse more easily without the need of repeating code

**Comment by marioncottard** [comment]
Okay it makes sense
