### ISSUE TITLE
Divide cornflow-app into two repositories

### ISSUE THREAD

**Issue by ggsdc** [baobabsoluciones/cornflow#196]
cornflow-app repository and user interface should be divided into two repositories:

* one should be a components library that can be reused in other interfaces such as cornflow-admin.
* the user interface of the default cornflow-app.

This means to move the current components that have been created in cornflow-app, for example, the calendar or the gantt. This way it should be easier to uses this components on other user interfaces and not have to copy paste code and maintain it on several places.

The library / package could be handled by version number, so that if a new component is needed on the user interface, just upgrading the package version should be enough to be able to use it.

**Comment by HelenaCA** [comment]
Implemented with cornflow-ui and mango-vue.
